### ISSUE TITLE
questions for visualvm remote monitoring java applications based on containers in k8s with jmx

### ISSUE THREAD

**Issue by hechuan73** [chanjarster/blog#1]
您好，
关于您 “visualvm-remote-monitoring-jmx-k8s.md”中对于远程监控k8s中的应用，我有几个问题想请教下：
1. “注意，-Djava.rmi.server.hostname一定要设置成localhost”
我现在想使用本地的jvisualvm监控远程k8s集群中的java应用，这个值是不是应该配置为Java应用所在节点的IP。

2. 我目前在启动参数中，配置了您所列举的6个参数，然后hostname配的应用所在节点的IP，然后将容器中的JMX端口映射到了对应的Node端口上，但是使用NodeIP:NodePort还是连接不上，请问您有遇到过类似情况吗？
谢谢！

**Comment by chanjarster** [comment]
你好，有问题请在这个链接里提出，我会在这个链接里回答：
